@extends('layouts.app')

@section('title', 'AI Alerts — ' . config('app.name'))

@section('content')

    <div class="page-head">
        <div>
            <h1 class="page-title">AI Alerts</h1>
            <p class="page-subtitle">Findings generated by the AI Security Bot — review, action and resolve.</p>
        </div>
        <div class="row-actions">
            @if (auth()->user()->role->canManageAlerts())
            <a href="{{ route('ai.export', request()->query()) }}" class="btn btn-secondary">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                Export Excel
            </a>
            @endif
            <a href="{{ route('ai.dashboard') }}" class="btn btn-ghost">Back to AI Dashboard</a>
        </div>
    </div>

    {{-- Summary stat cards --}}
    <section class="stats-grid stats-grid-4">
        <div class="stat-card">
            <div class="stat-top">
                <span class="stat-icon" aria-hidden="true">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
                </span>
                <span class="stat-value">{{ $stats['total'] }}</span>
            </div>
            <div class="stat-label">Total AI Alerts</div>
            <div class="stat-meta">All time</div>
        </div>
        <div class="stat-card stat-danger">
            <div class="stat-top">
                <span class="stat-icon" aria-hidden="true">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                </span>
                <span class="stat-value">{{ $stats['critical'] + $stats['high'] }}</span>
            </div>
            <div class="stat-label">Critical + High</div>
            <div class="stat-meta">Priority findings</div>
        </div>
        <div class="stat-card stat-warning">
            <div class="stat-top">
                <span class="stat-icon" aria-hidden="true">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                </span>
                <span class="stat-value">{{ $stats['open'] }}</span>
            </div>
            <div class="stat-label">Open</div>
            <div class="stat-meta">New + reviewing</div>
        </div>
        <div class="stat-card stat-success">
            <div class="stat-top">
                <span class="stat-icon" aria-hidden="true">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
                </span>
                <span class="stat-value">{{ $stats['accuracy'] }}%</span>
            </div>
            <div class="stat-label">AI Accuracy</div>
            <div class="stat-meta">Confirmed genuine after review</div>
        </div>
    </section>

    {{-- Search & filters --}}
    <form method="GET" action="{{ route('ai.alerts') }}" class="panel filters-bar" role="search">
        <div class="filter-field filter-grow">
            <label for="search">Search</label>
            <input type="search" id="search" name="search" value="{{ request('search') }}" placeholder="Alert ID, event type or description…">
        </div>

        <div class="filter-field">
            <label for="risk">Risk Level</label>
            <select id="risk" name="risk">
                <option value="">All</option>
                @foreach ($riskLevels as $level)
                    <option value="{{ $level->value }}" @selected(request('risk') === $level->value)>{{ $level->label() }}</option>
                @endforeach
            </select>
        </div>

        <div class="filter-field">
            <label for="status">Status</label>
            <select id="status" name="status">
                <option value="">All</option>
                @foreach ($statuses as $status)
                    <option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>
                @endforeach
            </select>
        </div>

        <div class="filter-field">
            <label for="event">Event Type</label>
            <select id="event" name="event">
                <option value="">All</option>
                @foreach ($eventTypes as $type)
                    <option value="{{ $type }}" @selected(request('event') === $type)>{{ $type }}</option>
                @endforeach
            </select>
        </div>

        <div class="filter-field">
            <label for="camera">Camera</label>
            <select id="camera" name="camera">
                <option value="">All</option>
                @foreach ($cameras as $id => $name)
                    <option value="{{ $id }}" @selected(request('camera') == $id)>{{ $name }}</option>
                @endforeach
            </select>
        </div>

        <div class="filter-field">
            <label for="employee">Employee</label>
            <select id="employee" name="employee">
                <option value="">All</option>
                @foreach ($employees as $id => $name)
                    <option value="{{ $id }}" @selected(request('employee') == $id)>{{ $name }}</option>
                @endforeach
            </select>
        </div>

        <div class="filter-field">
            <label for="from">From</label>
            <input type="date" id="from" name="from" value="{{ request('from') }}">
        </div>

        <div class="filter-field">
            <label for="to">To</label>
            <input type="date" id="to" name="to" value="{{ request('to') }}">
        </div>

        <div class="filter-actions">
            <button type="submit" class="btn btn-secondary">Filter</button>
            @if (request()->hasAny(['search', 'risk', 'status', 'event', 'camera', 'employee', 'from', 'to']))
                <a href="{{ route('ai.alerts') }}" class="btn btn-ghost">Reset</a>
            @endif
        </div>
    </form>

    {{-- AI alerts table --}}
    <section class="panel panel-flush">
        <div class="table-wrap">
            <table>
                <thead>
                    <tr>
                        <th>Alert ID</th>
                        <th>Event Type</th>
                        <th>Risk Level</th>
                        <th>Recommendation</th>
                        <th>Person</th>
                        <th>Location</th>
                        <th>Status</th>
                        <th>Date &amp; Time</th>
                        <th class="th-actions">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($alerts as $alert)
                        <tr>
                            <td class="mono">{{ $alert->ai_code }}</td>
                            <td>
                                {{ $alert->event_type }}
                                <div class="cell-sub" title="{{ $alert->description }}">{{ \Illuminate\Support\Str::limit($alert->description, 55) }}</div>
                            </td>
                            <td><span class="badge {{ $alert->risk_level->badge() }}" title="{{ $alert->analysis }}"><span class="badge-indicator" aria-hidden="true"></span>{{ $alert->risk_level->label() }} ({{ $alert->risk_score }})</span></td>
                            <td><span class="badge {{ $alert->recommendation->badge() }}">{{ $alert->recommendation->label() }}</span></td>
                            <td>{{ $alert->personLabel() ?? '—' }}</td>
                            <td>
                                {{ $alert->locationLabel() }}
                                @if ($alert->camera)
                                    <div class="cell-sub">Camera: {{ $alert->camera->name }}</div>
                                @endif
                            </td>
                            <td><span class="badge {{ $alert->status->badge() }}">{{ $alert->status->label() }}</span></td>
                            <td>
                                {{ $alert->happened_at->format('Y-m-d') }}
                                <div class="cell-sub mono">{{ $alert->happened_at->format('H:i:s') }}</div>
                            </td>
                            <td>
                                <div class="row-actions">
                                    <button type="button" class="action-btn js-view" title="View & Manage"
                                            aria-label="View {{ $alert->ai_code }}"
                                            data-code="{{ $alert->ai_code }}"
                                            data-when="{{ $alert->happened_at->format('M j, Y — H:i:s') }}"
                                            data-event="{{ $alert->event_type }}"
                                            data-risk="{{ $alert->risk_level->label() }} — score {{ $alert->risk_score }}/100"
                                            data-risk-badge="{{ $alert->risk_level->badge() }}"
                                            data-recommendation="{{ $alert->recommendation->label() }}"
                                            data-location="{{ $alert->locationLabel() }} ({{ $alert->building ?? '—' }}, {{ $alert->floor ?? '—' }})"
                                            data-camera="{{ $alert->camera?->name ?? '—' }}"
                                            data-person="{{ $alert->personLabel() ?? '—' }}"
                                            data-description="{{ $alert->description }}"
                                            data-analysis="{{ $alert->analysis }}"
                                            data-reviewed="{{ $alert->reviewer ? $alert->reviewer->name.($alert->resolved_at ? ' — resolved '.$alert->resolved_at->diffForHumans() : '') : '—' }}"
                                            data-status="{{ $alert->status->value }}"
                                            data-notes="{{ $alert->notes }}"
                                            data-action="{{ route('ai.alerts.update', $alert) }}">
                                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7z"/><circle cx="12" cy="12" r="3"/></svg>
                                    </button>
                                    @if ($alert->status->isOpen() && auth()->user()->can('update', $alert))
                                        <form method="POST" action="{{ route('ai.alerts.resolve', $alert) }}">
                                            @csrf
                                            <button type="submit" class="action-btn" title="Resolve" aria-label="Resolve {{ $alert->ai_code }}">
                                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 6L9 17l-5-5"/></svg>
                                            </button>
                                        </form>
                                    @endif
                                    @can('delete', $alert)
                                        <button type="button" class="action-btn action-danger js-delete" title="Delete"
                                                aria-label="Delete {{ $alert->ai_code }}"
                                                data-action="{{ route('ai.alerts.destroy', $alert) }}"
                                                data-name="{{ $alert->ai_code }} ({{ $alert->event_type }})">
                                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
                                        </button>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="9" class="table-empty">No AI alerts match your search or filters.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if ($alerts->hasPages())
            <div class="table-footer">
                {{ $alerts->links('pagination.app') }}
            </div>
        @endif
    </section>

    <x-delete-modal title="Delete AI Alert" message="Are you sure you want to delete this AI alert?" />

    {{-- AI alert details & management modal --}}
    <div class="modal-backdrop" id="view-modal" hidden>
        <div class="modal modal-wide" role="dialog" aria-modal="true" aria-labelledby="view-modal-title">
            <h3 class="modal-title" id="view-modal-title">AI Alert — <span class="mono" id="v-code"></span></h3>

            <dl class="profile-grid">
                <div class="profile-item"><dt>Date &amp; Time</dt><dd id="v-when"></dd></div>
                <div class="profile-item"><dt>Event Type</dt><dd id="v-event"></dd></div>
                <div class="profile-item"><dt>Risk Level</dt><dd><span class="badge" id="v-risk"><span class="badge-indicator" aria-hidden="true"></span><span id="v-risk-text"></span></span></dd></div>
                <div class="profile-item"><dt>Recommendation</dt><dd id="v-recommendation"></dd></div>
                <div class="profile-item"><dt>Location</dt><dd id="v-location"></dd></div>
                <div class="profile-item"><dt>Camera</dt><dd id="v-camera"></dd></div>
                <div class="profile-item"><dt>Related Person</dt><dd id="v-person"></dd></div>
                <div class="profile-item"><dt>Reviewed By</dt><dd id="v-reviewed"></dd></div>
                <div class="profile-item profile-item-wide"><dt>Description</dt><dd id="v-description"></dd></div>
                <div class="profile-item profile-item-wide"><dt>AI Analysis</dt><dd id="v-analysis"></dd></div>
            </dl>

            @if (auth()->user()->role->canManageAlerts())
            <form method="POST" id="view-form" data-loading>
                @csrf
                @method('PATCH')
                <h3 class="form-section-title">Manage Alert</h3>
                <div class="form-grid">
                    <div class="form-field">
                        <label for="v-status-input">Status</label>
                        <select id="v-status-input" name="status">
                            @foreach ($statuses as $status)
                                <option value="{{ $status->value }}">{{ $status->label() }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-field form-field-full">
                        <label for="v-notes-input">Notes</label>
                        <textarea id="v-notes-input" name="notes" rows="3" maxlength="1000" placeholder="Investigation notes…"></textarea>
                    </div>
                </div>
                <div class="modal-actions">
                    <button type="button" class="btn btn-ghost" data-close-view>Close</button>
                    <button type="submit" class="btn btn-primary" data-loading-text="Saving…">Save Changes</button>
                </div>
            </form>
            @else
                <div class="modal-actions">
                    <button type="button" class="btn btn-ghost" data-close-view>Close</button>
                </div>
            @endif
        </div>
    </div>

@endsection

@push('scripts')
<script>
    (() => {
        const viewModal = document.getElementById('view-modal');
        const viewForm = document.getElementById('view-form');
        const set = (id, text) => { const el = document.getElementById(id); if (el) el.textContent = text; };

        document.querySelectorAll('.js-view').forEach((btn) => {
            btn.addEventListener('click', () => {
                set('v-code', btn.dataset.code);
                set('v-when', btn.dataset.when);
                set('v-event', btn.dataset.event);
                set('v-risk-text', btn.dataset.risk);
                document.getElementById('v-risk').className = 'badge ' + btn.dataset.riskBadge;
                set('v-recommendation', btn.dataset.recommendation);
                set('v-location', btn.dataset.location);
                set('v-camera', btn.dataset.camera);
                set('v-person', btn.dataset.person);
                set('v-reviewed', btn.dataset.reviewed);
                set('v-description', btn.dataset.description);
                set('v-analysis', btn.dataset.analysis);
                if (viewForm) {
                    viewForm.action = btn.dataset.action;
                    document.getElementById('v-status-input').value = btn.dataset.status;
                    document.getElementById('v-notes-input').value = btn.dataset.notes || '';
                }
                viewModal.hidden = false;
            });
        });

        viewModal.addEventListener('click', (e) => {
            if (e.target === viewModal || e.target.closest('[data-close-view]')) viewModal.hidden = true;
        });

        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') viewModal.hidden = true;
        });
    })();
</script>
@endpush
